apiVersion: v1
kind: Service
metadata:
  name: svc-stockpilot-ms-ta-movavg
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  stockpilot-ms-ta-movavg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockpilot-ms-ta-movavg
spec:
  selector:
    matchLabels:
      app: stockpilot-ms-ta-movavg
  replicas: 2
  template:
    metadata:
      labels:
        app: stockpilot-ms-ta-movavg
    spec:
      containers:
      - name: stockpilot-ms-ta-movavg
        image: lakshanbanneheke/stockpilot-ms-ta-movavg:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: envs-config
        env:
          - name: FLASK_APP
            value: "app.py"
          - name: FLASK_RUN_PORT
            value: "80"
          - name: SECRET_KEY
            value: "stockpilot"
          - name: MONGO_URL_GENERAL
            value: "mongodb+srv://SEPU02:general123@sepcluster.yjn4m.mongodb.net/test_sep?retryWrites=true&w=majority"
          - name: MONGO_URL_ADMIN
            value: "mongodb+srv://SEPU01:User123@sepcluster.yjn4m.mongodb.net/test_sep?retryWrites=true&w=majority"
